Repository Cultura-Colectiva-Tech/docker-tools, pull requests merged in 2018-03, with the labels that each got.

#1 Configuration file for golang with mongodb
  envs/Coatlicue
Labels: enhancement

#2 Microservice Tonatiuh
  .github/PULL_REQUEST_TEMPLATE.md
  envs/tonatiuh
  wrappers/yarn.sh
Labels: enhancement

#3 Rename env microservice files
  envs/Kaliman
  envs/Tonatiuh
Labels: enhancement

#6 Comment out the second docker exec
  wrappers/yarn.sh
Labels: bug

#7 Add Kukulkan Frontend service
  envs/Kukulkan
Labels: enhancement

#8 Add wrapper mongo && Update cleaner wrappers
  cleaners/db.sh
  envs/Tonatiuh
  wrappers/mongo.sh
Labels: bug, enhancement

#10 Add alushe env
  envs/Alushe
Labels: enhancement

#11 Fix typo in name of Quetzalcoatl
  envs/Quetzalcoatl
Labels: bug
